import Link from 'next/link'
import { ArrowLeft, Shield } from 'lucide-react'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-babyblue-50 via-white to-babyblue-100">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-sm border-b border-babyblue-100 sticky top-0 z-50">
        <div className="max-w-3xl mx-auto px-4 py-4">
          <div className="flex items-center gap-3">
            <Link 
              href="/" 
              className="w-10 h-10 rounded-xl bg-babyblue-50 hover:bg-babyblue-100 flex items-center justify-center text-babyblue-600 transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div className="flex items-center gap-2">
              <Shield className="w-6 h-6 text-babyblue-500" />
              <h1 className="text-xl font-bold text-gray-900">Privacy Policy</h1>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8">
        <div className="bg-white rounded-2xl shadow-sm border border-babyblue-100 p-6 md:p-8">
          <p className="text-sm text-gray-500 mb-8">Last updated: April 3rd, 2026</p>

          <div className="prose prose-gray max-w-none">
            <p className="text-gray-600 leading-relaxed mb-6">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Interpretation and Definitions</h2>
            
            <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">Interpretation</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">Definitions</h3>
            <p className="text-gray-600 leading-relaxed mb-4">For the purposes of this Privacy Policy:</p>
            
            <ul className="space-y-3 text-gray-600 mb-6">
              <li><strong className="text-gray-900">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              <li><strong className="text-gray-900">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to UReppTV.</li>
              <li><strong className="text-gray-900">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong className="text-gray-900">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong className="text-gray-900">Website</strong> refers to URepp, accessible from https://urepp.vercel.app</li>
              <li><strong className="text-gray-900">Service</strong> refers to the Website.</li>
              <li><strong className="text-gray-900">Country</strong> refers to: Sacramento, United States</li>
              <li><strong className="text-gray-900">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong className="text-gray-900">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong className="text-gray-900">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong className="text-gray-900">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong className="text-gray-900">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            </ul>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Collecting and Using Your Personal Data</h2>

            <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">Types of Data Collected</h3>

            <h4 className="text-base font-semibold text-gray-900 mt-4 mb-2">Personal Data</h4>
            <p className="text-gray-600 leading-relaxed mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-gray-600 mb-6">
              <li>Email address</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-base font-semibold text-gray-900 mt-4 mb-2">Usage Data</h4>
            <p className="text-gray-600 leading-relaxed mb-4">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="text-gray-600 leading-relaxed mb-4">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>

            <h4 className="text-base font-semibold text-gray-900 mt-4 mb-2">Tracking Technologies and Cookies</h4>
            <p className="text-gray-600 leading-relaxed mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
            <p className="text-gray-600 leading-relaxed mb-4">
              You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Use of Your Personal Data</h2>
            <p className="text-gray-600 leading-relaxed mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="space-y-3 text-gray-600 mb-6">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
              <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
              <li>To manage Your requests: To attend and manage Your requests to Us.</li>
            </ul>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Retention of Your Personal Data</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Transfer of Your Personal Data</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Disclosure of Your Personal Data</h2>
            <p className="text-gray-600 leading-relaxed mb-4">We may share your personal information in the following situations:</p>
            <ul className="space-y-3 text-gray-600 mb-6">
              <li><strong className="text-gray-900">With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
              <li><strong className="text-gray-900">For Business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
              <li><strong className="text-gray-900">With Affiliates:</strong> We may share Your information with Our affiliates.</li>
              <li><strong className="text-gray-900">With Business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
            </ul>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Security of Your Personal Data</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Children's Privacy</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Links to Other Websites</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Changes to this Privacy Policy</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">Contact Us</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p className="text-gray-600">
              By email: <a href="mailto:alex@urepp.tv" className="text-babyblue-600 hover:underline">alex@urepp.tv</a>
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}
